name: Build

on:
    push:
        branches: [ '**' ]
    schedule:
        -   cron: '0 0 * * *'

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: docker.io
    IMAGE_NAME: enabel/phpqa

jobs:
    push_to_registry:
        strategy:
            matrix:
                branches: [ main, 8.2, 8.1 ]
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v3
                with:
                    ref: ${{ matrix.branches }}

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Log in to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v4
                with:
                    tags: |
                        type=raw,value=${
                          if contains(matrix.branches, 'main') && github.ref == 'refs/heads/main' {
                            'latest'
                          } else {
                            matrix.branches
                          }
                        },
                        enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
